Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(rw_with_food_multiple_walkers.py:16564): Gdk-CRITICAL **: 18:05:54.326: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(rw_with_food_multiple_walkers.py:16564): Gdk-CRITICAL **: 18:05:54.344: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
2078.5672371573746
Fertig
